# Generated by Django 4.0.6 on 2024-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='featured_image/default.jpg', upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
