# Generated by Django 3.2.6 on 2024-03-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240326_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='postfile',
            options={'verbose_name': 'Файл к статье', 'verbose_name_plural': 'Файлы к статье'},
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Статья'),
        ),
    ]
